_security_logout:
    resource: security.route_loader.logout
    type: service

# security:
#   role_hierarchy:
#     ROLE_TRANSPORTEUR: [ROLE_USER]
#     ROLE_SUPER_ADMIN: [ROLE_TRANSPORTEUR, ROLE_ALLOWED_TO_SWITCH]